server:
  port: 8080
  servlet:
    context-path: /api-jplag

spring:
  servlet:
    multipart:
      enabled: true
#      单文件请求最大限制
      max-file-size: 100MB
#      单次请求最大限制
      max-request-size: 1000MB

custom:
#  前端项目BaseUrl
#  fronted_base_url: http://your/fronted/base/url;http://localhost
#  用于该项目暂存文件的目录
  base-resource-path: E:\Desktop\WebProject\CodeJPlag-main\backend\src\main\resources